//! aarch64 guest syscall table (asm-generic numbering).
//!
//! On arm64 the syscall number is in `x8`, args in `x0..x5`, return in `x0`.

use super::Sysno;

/// Map a raw aarch64 syscall number to the normalized [`Sysno`].
#[must_use]
pub fn decode(nr: u64) -> Sysno {
    match nr {
        63 => Sysno::Read,
        64 => Sysno::Write,
        56 => Sysno::Openat,
        57 => Sysno::Close,
        214 => Sysno::Brk,
        222 => Sysno::Mmap,
        215 => Sysno::Munmap,
        226 => Sysno::Mprotect,
        94 => Sysno::ExitGroup,
        93 => Sysno::Exit,
        96 => Sysno::SetTidAddress,
        29 => Sysno::Ioctl,
        66 => Sysno::Writev,
        160 => Sysno::Uname,
        172 => Sysno::Getpid,
        173 => Sysno::Getppid,
        178 => Sysno::Gettid,
        174 => Sysno::Getuid,
        175 => Sysno::Geteuid,
        176 => Sysno::Getgid,
        177 => Sysno::Getegid,
        113 => Sysno::ClockGettime,
        62 => Sysno::Lseek,
        80 => Sysno::Fstat,
        79 => Sysno::Newfstatat,
        61 => Sysno::Getdents64,
        17 => Sysno::Getcwd,
        49 => Sysno::Chdir,
        278 => Sysno::Getrandom,
        134 => Sysno::RtSigaction,
        135 => Sysno::RtSigprocmask,
        98 => Sysno::Futex,
        25 => Sysno::Fcntl,
        59 => Sysno::Pipe2,
        23 => Sysno::Dup,
        24 => Sysno::Dup3,
        220 => Sysno::Clone,
        221 => Sysno::Execve,
        260 => Sysno::Wait4,
        99 => Sysno::SetRobustList,
        43 => Sysno::Statfs,
        44 => Sysno::Fstatfs,
        78 => Sysno::Readlinkat,
        36 => Sysno::Symlinkat,
        34 => Sysno::Mkdirat,
        35 => Sysno::Unlinkat,
        276 => Sysno::Renameat2,
        48 => Sysno::Faccessat,
        439 => Sysno::Faccessat2,
        53 => Sysno::Fchmodat,
        52 => Sysno::Fchmod,
        54 => Sysno::Fchownat,
        55 => Sysno::Fchown,
        88 => Sysno::Utimensat,
        166 => Sysno::Umask,
        8 => Sysno::Getxattr,
        9 => Sysno::Lgetxattr,
        10 => Sysno::Fgetxattr,
        198 => Sysno::Socket,
        199 => Sysno::Socketpair,
        200 => Sysno::Bind,
        201 => Sysno::Listen,
        242 => Sysno::Accept4,
        203 => Sysno::Connect,
        204 => Sysno::Getsockname,
        205 => Sysno::Getpeername,
        206 => Sysno::Sendto,
        207 => Sysno::Recvfrom,
        208 => Sysno::Setsockopt,
        209 => Sysno::Getsockopt,
        210 => Sysno::Shutdown,
        other => Sysno::Unknown(other),
    }
}
