//! Per-architecture ABI tables.
//!
//! The kernel dispatches on a *normalized* [`Sysno`] so handlers are written
//! once; these tables map raw guest syscall numbers to that enum.

pub mod aarch64;
pub mod x86_64;

use crate::abi::Arch;

/// Architecture-neutral syscall identity.
///
/// Guest arm64 and x86-64 use different raw numbers for the same operation; the
/// kernel works in terms of this enum. Only a starter set is listed — entries
/// are added as handlers come online (see ROADMAP phases).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum Sysno {
    Read,
    Write,
    Openat,
    Close,
    Brk,
    Mmap,
    Munmap,
    Mprotect,
    Mremap,
    Madvise,
    Mlock,
    Mlock2,
    Munlock,
    Mlockall,
    Munlockall,
    Msync,
    Mincore,
    ExitGroup,
    Exit,
    SetTidAddress,
    Ioctl,
    Readv,
    Writev,
    Setitimer,
    Getitimer,
    Alarm,
    Uname,
    Getpid,
    Getppid,
    Gettid,
    Getuid,
    Geteuid,
    Getgid,
    Getegid,
    ClockGettime,
    Gettimeofday,
    ClockGetres,
    Nanosleep,
    ClockNanosleep,
    ClockSettime,
    Settimeofday,
    Adjtimex,
    ClockAdjtime,
    Time,
    Lseek,
    Fstat,
    Newfstatat,
    Getdents64,
    Getcwd,
    Chdir,
    Fchdir,
    Getrandom,
    RtSigaction,
    RtSigprocmask,
    RtSigpending,
    RtSigsuspend,
    RtSigtimedwait,
    RtSigqueueinfo,
    RtTgsigqueueinfo,
    RtSigreturn,
    Sigaltstack,
    Kill,
    Tkill,
    Tgkill,
    Futex,
    Fcntl,
    Flock,
    Sendmsg,
    Recvmsg,
    Pipe2,
    Dup,
    Dup2,
    Dup3,
    Clone,
    /// x86-64 only (aarch64 has no `fork` syscall — everything is `clone`).
    Fork,
    /// x86-64 only, like [`Sysno::Fork`].
    Vfork,
    /// x86-64 only (aarch64 has no path-based `stat` — only `newfstatat`).
    Stat,
    /// x86-64 only, like [`Sysno::Stat`].
    Lstat,
    /// x86-64 only: the legacy path-based file syscalls aarch64 replaced
    /// with their `*at` successors. Each dispatches as `<op>at(AT_FDCWD, …)`.
    Open,
    /// x86-64 only — `open(path, O_WRONLY|O_CREAT|O_TRUNC, mode)`.
    Creat,
    /// x86-64 only, like [`Sysno::Open`].
    Mkdir,
    /// x86-64 only — `unlinkat(AT_FDCWD, path, AT_REMOVEDIR)`.
    Rmdir,
    /// x86-64 only, like [`Sysno::Open`].
    Unlink,
    /// x86-64 only, like [`Sysno::Open`].
    Rename,
    /// x86-64 only, like [`Sysno::Open`].
    Symlink,
    /// x86-64 only, like [`Sysno::Open`].
    Readlink,
    Execve,
    Wait4,
    SetRobustList,
    Statfs,
    Fstatfs,
    Readlinkat,
    Symlinkat,
    Mkdirat,
    Unlinkat,
    Renameat,
    Renameat2,
    Faccessat,
    Faccessat2,
    Access,
    Fchmodat,
    Chmod,
    Fchmod,
    Fchownat,
    Fchown,
    /// x86-64 only — `chown(path, uid, gid)`, follows symlinks.
    Chown,
    /// x86-64 only — `lchown(path, uid, gid)`, acts on the link itself.
    Lchown,
    /// Create a special file (`mknod(path, mode, dev)`); x86-64 only.
    Mknod,
    /// Create a special file relative to a dirfd (`mknodat`).
    Mknodat,
    Utimensat,
    Umask,
    Getxattr,
    Lgetxattr,
    Fgetxattr,
    Socket,
    Socketpair,
    Bind,
    Listen,
    Accept4,
    Connect,
    Getsockname,
    Getpeername,
    Sendto,
    Recvfrom,
    Setsockopt,
    Getsockopt,
    Shutdown,
    SchedYield,
    SchedGetaffinity,
    SchedSetaffinity,
    SchedGetscheduler,
    SchedSetscheduler,
    SchedGetparam,
    SchedGetPriorityMax,
    SchedGetPriorityMin,
    Getrusage,
    Sysinfo,
    Prlimit64,
    Getrlimit,
    Setrlimit,
    Times,
    Getpriority,
    Setpriority,
    Getcpu,
    Prctl,
    Personality,
    Sethostname,
    Setdomainname,
    Capget,
    Capset,
    Membarrier,
    // ---- event-notification / readiness syscalls ----
    Poll,
    Ppoll,
    Select,
    Pselect6,
    EpollCreate,
    EpollCreate1,
    EpollCtl,
    EpollWait,
    EpollPwait,
    EpollPwait2,
    Eventfd,
    Eventfd2,
    TimerfdCreate,
    TimerfdSettime,
    TimerfdGettime,
    /// x86-64-only: set the FS/GS segment base (used for TLS). No aarch64
    /// equivalent (arm64 TLS goes through `TPIDR_EL0`, set directly by the
    /// vcpu on thread creation).
    ArchPrctl,
    // ---- positioned & vectored I/O ----
    Pread64,
    Pwrite64,
    Preadv,
    Pwritev,
    // ---- file size / sync ----
    Ftruncate,
    Truncate,
    Fsync,
    Fdatasync,
    Sync,
    Syncfs,
    Fallocate,
    Readahead,
    Fadvise64,
    SyncFileRange,
    // ---- file copy / link ----
    Sendfile,
    CopyFileRange,
    Link,
    Linkat,
    Statx,
    // ---- credentials (root no-ops) ----
    Setuid,
    Setgid,
    Setreuid,
    Setregid,
    Setresuid,
    Setresgid,
    Getresuid,
    Getresgid,
    Setfsuid,
    Setfsgid,
    Getgroups,
    Setgroups,
    // ---- process groups / sessions ----
    Setpgid,
    Getpgid,
    Getpgrp,
    Setsid,
    Getsid,
    // ---- process lifecycle ----
    Waitid,
    Clone3,
    Execveat,
    CloseRange,
    // ---- sockets ----
    Accept,
    Recvmmsg,
    Sendmmsg,
    // ---- misc / stubs ----
    Syslog,
    Mount,
    Umount2,
    Chroot,
    Ptrace,
    Rseq,
    RestartSyscall,
    GetRobustList,
    MemfdCreate,
    InotifyInit1,
    InotifyAddWatch,
    InotifyRmWatch,
    Signalfd4,
    Pause,
    // ---- x86-64 legacy spellings of syscalls aarch64 only has in `*at`/`2`
    // form (each dispatches to the modern handler with the old arg shape) ----
    /// x86-64 only — `pipe(fds)`: `pipe2(fds, 0)` (the second register is
    /// whatever the caller left there, so it must not be read as flags).
    Pipe,
    /// x86-64 only — `getdents(fd, buf, count)`: the old `linux_dirent` layout
    /// (`d_type` in the record's last byte), not `linux_dirent64`.
    Getdents,
    /// x86-64 only — `utime(path, struct utimbuf *)` (whole seconds).
    Utime,
    /// x86-64 only — `utimes(path, struct timeval[2])`.
    Utimes,
    /// x86-64 only — `futimesat(dirfd, path, struct timeval[2])`.
    Futimesat,
    /// x86-64 only — `signalfd(fd, mask, sizemask)` (= `signalfd4(.., 0)`).
    Signalfd,
    /// x86-64 only — `inotify_init()` (= `inotify_init1(0)`).
    InotifyInit,
    /// `fchmodat2(dirfd, path, mode, flags)` — `fchmodat` with real flags.
    Fchmodat2,
    // ---- extended attributes ----
    Setxattr,
    Lsetxattr,
    Fsetxattr,
    Listxattr,
    Llistxattr,
    Flistxattr,
    Removexattr,
    Lremovexattr,
    Fremovexattr,
    /// `setxattrat(dirfd, path, at_flags, name, struct xattr_args *, size)`.
    Setxattrat,
    Getxattrat,
    Listxattrat,
    Removexattrat,
    // ---- I/O priority / pipes-as-buffers ----
    IoprioSet,
    IoprioGet,
    Splice,
    Tee,
    Vmsplice,
    Preadv2,
    Pwritev2,
    Openat2,
    Cachestat,
    // ---- POSIX timers ----
    TimerCreate,
    TimerSettime,
    TimerGettime,
    TimerGetoverrun,
    TimerDelete,
    // ---- scheduling ----
    SchedSetparam,
    SchedRrGetInterval,
    SchedSetattr,
    SchedGetattr,
    // ---- POSIX message queues ----
    MqOpen,
    MqUnlink,
    MqTimedsend,
    MqTimedreceive,
    MqNotify,
    MqGetsetattr,
    // ---- System V IPC ----
    Msgget,
    Msgsnd,
    Msgrcv,
    Msgctl,
    Semget,
    Semop,
    Semtimedop,
    Semctl,
    Shmget,
    Shmat,
    Shmdt,
    Shmctl,
    // ---- NUMA memory policy (a single node) ----
    Mbind,
    GetMempolicy,
    SetMempolicy,
    MigratePages,
    MovePages,
    SetMempolicyHomeNode,
    // ---- cross-process ----
    ProcessVmReadv,
    ProcessVmWritev,
    ProcessMadvise,
    ProcessMrelease,
    Kcmp,
    PidfdOpen,
    PidfdSendSignal,
    PidfdGetfd,
    // ---- memory protection keys / sealing ----
    PkeyMprotect,
    PkeyAlloc,
    PkeyFree,
    Mseal,
    RemapFilePages,
    // ---- futex2 ----
    FutexWaitv,
    FutexWake,
    FutexWait,
    FutexRequeue,
    // ---- sandboxing / namespaces ----
    Seccomp,
    Unshare,
    Setns,
    // ---- legacy x86-64 odds and ends with a real (if minimal) answer ----
    Ustat,
    Sysfs,
    Vhangup,
    Iopl,
    Ioperm,
    Reboot,
    // ---- deliberately unavailable: decoded so they are *not* counted as
    // unknown, each answering what a Linux kernel built without the feature
    // (or a container without the capability) answers, so feature probes fall
    // back cleanly. See `Kernel::sys_unavailable` for the per-syscall errno.
    IoSetup,
    IoDestroy,
    IoSubmit,
    IoCancel,
    IoGetevents,
    IoPgetevents,
    IoUringSetup,
    IoUringEnter,
    IoUringRegister,
    PerfEventOpen,
    Bpf,
    Userfaultfd,
    FanotifyInit,
    FanotifyMark,
    NameToHandleAt,
    OpenByHandleAt,
    KexecLoad,
    KexecFileLoad,
    InitModule,
    FinitModule,
    DeleteModule,
    Swapon,
    Swapoff,
    Acct,
    Quotactl,
    QuotactlFd,
    PivotRoot,
    OpenTree,
    OpenTreeAttr,
    MoveMount,
    Fsopen,
    Fsconfig,
    Fsmount,
    Fspick,
    MountSetattr,
    Statmount,
    Listmount,
    LandlockCreateRuleset,
    LandlockAddRule,
    LandlockRestrictSelf,
    AddKey,
    RequestKey,
    Keyctl,
    MemfdSecret,
    MapShadowStack,
    LsmGetSelfAttr,
    LsmSetSelfAttr,
    LsmListModules,
    FileGetattr,
    FileSetattr,
    /// x86-64 legacy LDT/GDT-TLS/`uselib`/`_sysctl` — see `sys_unavailable`.
    ModifyLdt,
    SetThreadArea,
    GetThreadArea,
    Uselib,
    Sysctl,
    /// x86-64 only — the uretprobe trampoline's private syscall.
    Uretprobe,
    /// A number the Linux table reserves but wires to `sys_ni_syscall`
    /// (`getpmsg`, `putpmsg`, `afs_syscall`, `tuxcall`, `security`, `vserver`,
    /// `create_module`, `get_kernel_syms`, `query_module`, `nfsservctl`,
    /// `lookup_dcookie`, `epoll_ctl_old`, `epoll_wait_old`): always `ENOSYS`,
    /// exactly as on real Linux, but *known* (not logged as unsupported).
    NiSyscall,
    /// A raw guest number with no mapping yet — handled as ENOSYS but logged.
    Unknown(u64),
}

/// Decode a raw guest syscall number for `arch` into the normalized [`Sysno`].
#[must_use]
pub fn decode(arch: Arch, nr: u64) -> Sysno {
    match arch {
        Arch::Aarch64 => aarch64::decode(nr),
        Arch::X86_64 => x86_64::decode(nr),
    }
}
