//! x86-64 guest syscall table.
//!
//! On x86-64 the syscall number is in `rax`, args in `rdi, rsi, rdx, r10, r8,
//! r9`, return in `rax`.

use super::Sysno;

/// Map a raw x86-64 syscall number to the normalized [`Sysno`].
#[must_use]
pub fn decode(nr: u64) -> Sysno {
    match nr {
        0 => Sysno::Read,
        1 => Sysno::Write,
        257 => Sysno::Openat,
        3 => Sysno::Close,
        12 => Sysno::Brk,
        9 => Sysno::Mmap,
        11 => Sysno::Munmap,
        10 => Sysno::Mprotect,
        231 => Sysno::ExitGroup,
        60 => Sysno::Exit,
        218 => Sysno::SetTidAddress,
        16 => Sysno::Ioctl,
        20 => Sysno::Writev,
        63 => Sysno::Uname,
        39 => Sysno::Getpid,
        110 => Sysno::Getppid,
        186 => Sysno::Gettid,
        102 => Sysno::Getuid,
        107 => Sysno::Geteuid,
        104 => Sysno::Getgid,
        108 => Sysno::Getegid,
        228 => Sysno::ClockGettime,
        96 => Sysno::Gettimeofday,
        229 => Sysno::ClockGetres,
        230 => Sysno::ClockNanosleep,
        35 => Sysno::Nanosleep,
        227 => Sysno::ClockSettime,
        164 => Sysno::Settimeofday,
        159 => Sysno::Adjtimex,
        305 => Sysno::ClockAdjtime,
        201 => Sysno::Time,
        8 => Sysno::Lseek,
        5 => Sysno::Fstat,
        262 => Sysno::Newfstatat,
        217 => Sysno::Getdents64,
        79 => Sysno::Getcwd,
        80 => Sysno::Chdir,
        318 => Sysno::Getrandom,
        13 => Sysno::RtSigaction,
        14 => Sysno::RtSigprocmask,
        202 => Sysno::Futex,
        72 => Sysno::Fcntl,
        293 => Sysno::Pipe2,
        32 => Sysno::Dup,
        33 => Sysno::Dup2,
        292 => Sysno::Dup3,
        56 => Sysno::Clone,
        59 => Sysno::Execve,
        61 => Sysno::Wait4,
        273 => Sysno::SetRobustList,
        137 => Sysno::Statfs,
        138 => Sysno::Fstatfs,
        267 => Sysno::Readlinkat,
        266 => Sysno::Symlinkat,
        258 => Sysno::Mkdirat,
        263 => Sysno::Unlinkat,
        264 => Sysno::Renameat,
        316 => Sysno::Renameat2,
        269 => Sysno::Faccessat,
        439 => Sysno::Faccessat2,
        21 => Sysno::Access,
        268 => Sysno::Fchmodat,
        91 => Sysno::Fchmod,
        260 => Sysno::Fchownat,
        93 => Sysno::Fchown,
        280 => Sysno::Utimensat,
        95 => Sysno::Umask,
        191 => Sysno::Getxattr,
        192 => Sysno::Lgetxattr,
        193 => Sysno::Fgetxattr,
        41 => Sysno::Socket,
        42 => Sysno::Connect,
        288 => Sysno::Accept4,
        44 => Sysno::Sendto,
        45 => Sysno::Recvfrom,
        48 => Sysno::Shutdown,
        49 => Sysno::Bind,
        50 => Sysno::Listen,
        51 => Sysno::Getsockname,
        52 => Sysno::Getpeername,
        53 => Sysno::Socketpair,
        54 => Sysno::Setsockopt,
        55 => Sysno::Getsockopt,
        other => Sysno::Unknown(other),
    }
}
